### ISSUE TITLE
Trade sometimes shows 0 for max amount

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#222]
It can happen that even when you have donkeys and wares in a storehouse, maybe one you also use only for trading and built it close to an allied storehouse, that you still get only " /0" als maximum amount. That way you have no chance to trade.

**Comment by Flamefire** [comment]
Can you reproduce this in a savegame?

**Comment by Flamefire** [comment]
Ok found the issue: The Tradegraph could not find a path, if the start and goal nodes were equal -> Guaranteed failure for distances of less than 20 game nodes.

**Comment by Spikeone** [comment]
This also happens sometime when you have wares.
I will try to reproduce this bug, if I can't this report can be closed

**Comment by Flamefire** [comment]
No need to reproduce. I have found the issue and it is fixed in my local branch. The path search simply failed if the warehouses are to close (not always though...)

**Comment by Spikeone** [comment]
Even when I could send other wares, I couldn't send some. That's also related to this bug?

**Comment by Flamefire** [comment]
When you want to send something it considers all warehouses with a possible path to the goal. The one closest to the goal does not get considered due to this bug. So the wares you CAN send originate in other warehouses.

**Comment by Spikeone** [comment]
Still, I had 10 gold and 10 generals in one storehouse, all other storehouses weren't allowed to store those goods.
I could send gold but not generals - I still don't see how this bug is explained then but okay, maybe that's fixed which is good :)

**Comment by Flamefire** [comment]
Don't know how this could happen. If you can reproduce this I'll check and make sure this does not happen again
